const DOCTORS = [
    {
      id: "d1",
      name: "Dr. Hansraj Mehta",
      specialty: "Cardiology",
      location: "Delhi",
      languages: ["English", "Hindi"],
      gender: "Male",
      about: "Board-certified cardiologist with 10+ years of experience.",
      photo: "https://avatar.iran.liara.run/public/32",
    },
    {
      id: "d2",
      name: "Dr. Manmohan Das",
      specialty: "Dermatology",
      location: "Mumbai",
      languages: ["English", "Hindi", "Marathi"],
      gender: "Male",
      about: "Dermatologist specializing in acne and eczema treatment.",
      photo: "https://avatar.iran.liara.run/public/37",
    },
    {
      id: "d3",
      name: "Dr. Aisha Khan",
      specialty: "Pediatrics",
      location: "West Bengal",
      languages: ["English", "Hindi", "Bengali"],
      gender: "Female",
      about: "Pediatrician focused on preventive care and family education.",
      photo: "https://avatar.iran.liara.run/public/68",
    },
    {
      id: "d5",
      name: "Dr. Rina Patel",
      specialty: "Gynecology",
      location: "Mumbai",
      languages: ["English", "Hindi"],
      gender: "Female",
      about: "Experienced gynecologist providing comprehensive women's health care.",
      photo: "https://avatar.iran.liara.run/public/99",
    },
    {
      id: "d6",
      name: "Dr. Rahul Verma",
      specialty: "Orthopedics",
      location: "Delhi",
      languages: ["English", "Hindi"],
      gender: "Male",
      about: "Orthopedic surgeon with a focus on sports injuries.",
      photo: "https://avatar.iran.liara.run/public/47",
    },
    {
        id: "d7",
        name: "Dr. Sneha Iyer",
        specialty: "Psychiatry",
        location: "Bangalore",
        languages: ["English", "Hindi", "Kannada"],
        gender: "Female",
        about: "Psychiatrist with a focus on adolescent mental health.",
        photo: "https://avatar.iran.liara.run/public/57",
    },
    {
        id: "d8",
        name: "Dr. Vikram Singh",
        specialty: "Cardiology",
        location: "Punjab",
        languages: ["English", "Hindi", "Punjabi"],
        gender: "Male",
        about: "Cardiologist with a focus on preventive care.",
        photo: "https://avatar.iran.liara.run/public/22",
    },
    
  ];

export default DOCTORS;